### ISSUE TITLE
provide documentation

### ISSUE THREAD

**Issue by cinghialino** [a-p-z/datetime-card#1]
there is no documentation with this repo.

**Comment by cjsmns** [comment]
I've tried a few different ways, and can't work out what how to set this up.

Documentation would be great.

**Comment by a-p-z** [comment]
First of all thanks for your feedback.
What kind of documentation would you like to have?

The steps to install the card are in the readme.

To configure it there is the card configuration interface:
![image](https://user-images.githubusercontent.com/27644989/169788039-41de629a-5819-47c0-ad29-ae2590fd43f4.png)

On it, you have to set 
- a title (optional)
- an image (optional, like "/local/an-image-that-you-have-in-www-folder.png"
- an input_datetime entity that you have already had defined (ex: input_datetime.plant_chinese_money_w)
- max is a threshold, if the number of days is less than max the bar is green, otherwise it is red

**Comment by cjsmns** [comment]
Interesting... It says `No visual editor available for type 'custom:datetime-card'.`

Looking at the screenshot you provided, I've managed to get one entity on there, but on the project page you have 3 entities. How did you get that?

This is what I have.

```
type: custom:datetime-card
entity:
  - input_datetime.christmas_day
max: 365
```

**Comment by a-p-z** [comment]
No visual editor? weird. I will try to reproduce and fix it
for the moment use this example to create yours
```
type: custom:datetime-card
title: Chinese money
image: /local/plant_chinese_money.png
entities:
  - id: input_datetime.plant_chinese_money_w
    max: 9
  - id: input_datetime.plant_chinese_money_m
    max: 5
  - id: input_datetime.plant_chinese_money_f
    max: 17
```
